"""add division store to transactions2

Revision ID: 730a6951858c
Revises: d18eb8d29259
Create Date: 2026-03-07 18:09:20.994581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730a6951858c'
down_revision: Union[str, None] = 'd18eb8d29259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('division', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('store', sa.String(length=100), nullable=True))
    op.add_column('transactions', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('transactions', 'justification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('justification', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'store')
    op.drop_column('transactions', 'division')
    # ### end Alembic commands ###