"""add subcategory to transactions

Revision ID: 81027efc7990
Revises: 730a6951858c
Create Date: 2026-03-07 22:41:24.618525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81027efc7990'
down_revision: Union[str, None] = '730a6951858c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('subcategory', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'subcategory')
    # ### end Alembic commands ###