"""add_password_reset_tokens

Revision ID: d906c60f1680
Revises: 6922ddc504d0
Create Date: 2026-03-06 23:11:37.773136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd906c60f1680'
down_revision: Union[str, None] = '6922ddc504d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('email_verification_tokens_token_key'), 'email_verification_tokens', type_='unique')
    op.drop_index(op.f('ix_evt_token'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_evt_user_id'), table_name='email_verification_tokens')
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('email_hmac', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('users_email_encrypted_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email_hmac'), 'users', ['email_hmac'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_hmac'), table_name='users')
    op.create_unique_constraint(op.f('users_email_encrypted_key'), 'users', ['email_encrypted'])
    op.drop_column('users', 'email_hmac')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.create_index(op.f('ix_evt_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_evt_token'), 'email_verification_tokens', ['token'], unique=False)
    op.create_unique_constraint(op.f('email_verification_tokens_token_key'), 'email_verification_tokens', ['token'])
    # ### end Alembic commands ###